{"name": "Search_by_q_param", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'response' referenced before assignment", "trace": "data = ['Ainsworth+east+4th+street+1', '42.5498912', '-99.8524355']\n\n    @allure.title(\"Search_by_q_param\")\n    @pytest.mark.parametrize('data', data)\n    def test_search_by_q(data):\n        '''Проверка эндпоинта search с параметром поиска в свободной форме'''\n        params = {\n                    'q': data[0],\n                    'format': 'json'\n                 }\n        try:\n            response = connection(TESTED_URL, params)\n        except ConnectionError as error:\n            logger.error(error)\n    \n        with allure.step(\"Проверяю, что широта соответствует ожидаемой\"):\n>           assert round(\n                float(response.json()[0]['lat']), ROUND_LEVEL\n                ) == round(float(data[1]), ROUND_LEVEL)\nE           UnboundLocalError: local variable 'response' referenced before assignment\n\ntest_OSM.py:46: UnboundLocalError"}, "description": "Проверка эндпоинта search с параметром поиска в свободной форме", "steps": [{"name": "Connection to server", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nodgminatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ainsworth%2Beast%2B4th%2Bstreet%2B1&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029534E10BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\dev\\test_OSM\\test_OSM.py\", line 28, in connection\n    response = get(tested_url, params=params)\n  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\requests\\api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"c:\\dev\\test_osm\\venv\\lib\\site-packages\\requests\\adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "parameters": [{"name": "tested_url", "value": "'https://nodgminatim.openstreetmap.org/search'"}, {"name": "params", "value": "{'q': 'Ainsworth+east+4th+street+1', 'format': 'json'}"}], "start": 1682510188541, "stop": 1682510188543}, {"name": "Проверяю, что широта соответствует ожидаемой", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'response' referenced before assignment\n", "trace": "  File \"C:\\dev\\test_OSM\\test_OSM.py\", line 46, in test_search_by_q\n    assert round(\n"}, "start": 1682510188546, "stop": 1682510188546}], "attachments": [{"name": "log", "source": "4315c684-29a9-477d-a730-a041b6b0f170-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "['Ainsworth+east+4th+street+1', '42.5498912', '-99.8524355']"}], "start": 1682510188540, "stop": 1682510188546, "uuid": "e5765406-f719-4ce1-a272-221d771fa000", "historyId": "5d54f4e35b1b71a0be2f281c00082580", "testCaseId": "ab3b001e204633f5d14053bd6104326d", "fullName": "test_OSM#test_search_by_q", "labels": [{"name": "suite", "value": "test_OSM"}, {"name": "host", "value": "DESKTOP-NTU09GJ"}, {"name": "thread", "value": "4072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_OSM"}]}