2023-04-26 14:56:28 [31m[1mERROR[0m HTTPSConnectionPool(host='nodgminatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?street=valapolku+9&city=+&county=+&state=+&country=+&postalcode=+&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029534E1A978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))