2023-04-26 14:39:16 [1m[31mERROR[0m HTTPSConnectionPool(host='nodminatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=3%2BPaulay%2Bede%2BHungary&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CA9AB48B00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))